### ISSUE TITLE
Curate NGEE-Arctic datasets for GVP

### ISSUE THREAD

**Issue by serbinsh** [plantphys/gsti#4]
Here is how I was doing this for my ngee paper: https://github.com/serbinsh/SSerbin_NGEEArctic_Spectra_Trait/blob/main/R_scripts/Curate_datasets/Curate_leaf_gasex_datasets.R

 But this is using the data fitted for the studies, I think you may want to fit again with the raw data

**Comment by JulienLamour** [comment]
Done and added to the database
