### ISSUE TITLE
Defining biomes for contributed data

### ISSUE THREAD

**Issue by serbinsh** [plantphys/gsti#42]
Some ideas for providing objective definitions:
https://www.nature.com/articles/sdata2018214

https://www.nature.com/articles/sdata2018214/figures/1

Biome defs by Olsson: https://github.com/TESTgroup-BNL/Global_Vcmax/blob/main/Vignettes/Biomes.csv

Köppen: https://en.wikipedia.org/wiki/K%C3%B6ppen_climate_classification

**Comment by JulienLamour** [comment]
We used Olson et al. 2001 list of biomes
