### ISSUE TITLE
Improve landing page model summary layout, stats and info

### ISSUE THREAD

**Issue by serbinsh** [plantphys/gsti#50]
I think we want to simplify the landing page model stats and info to include a more concise summary.  We can add a new page to link to with more detailed info but at the moment the layout is a little messy plus the long species table stretches the page and is only going to get longer. Suggest maybe we do something like a genus table or higher level summary on the main landing page, with a map a spectra figure and a current model stats/fit figure layed out a bit more cleanly below the info

**Comment by JulienLamour** [comment]
The reflectance figure with jumps at 500 nm and 900 nm is caused by a subset of measurements in the wavelength 500 to 900 while many other measurements are in full range.

**Comment by serbinsh** [comment]
I forgot about this issue.  A related issue: https://github.com/TESTgroup-BNL/gsti/issues/55 

I'll work on some redesign of the landing page such that we dont have the massive species table displayed and I think we should go back to having the latest PLSR model showing with the spectra and the PDF of Vcmax
