### ISSUE TITLE
Dataset cleanup and/or sanity checks

### ISSUE THREAD

**Issue by serbinsh** [plantphys/gsti#55]
@JulienLamour FYI - some of the new datasets have issues with their spectra that stem from the use of ASD spectrometers and/or those that dont provide "jump corrected" spectra.  You can see below the spectral edges/discontinuities that need to be fixed or removed from our database otherwise they will artificially impact the accuracy of our fits and throw off our model. These spectral issues are not something we should embed in our models and are things that should be corrected by the data provider and / or using R packages that process spectral data

For example in my most recent look at the data we now have specta issues
![Reflectance](https://github.com/TESTgroup-BNL/gsti/assets/3067369/ac3d2fe5-60a6-40c6-a1d7-87db835762d0)

The easiest thing to do right now is drop any new data with these issues and later on figure out how to automate the detection of issues like this or others like erroneous Vcmax values

**Comment by JulienLamour** [comment]
@serbinsh This is not an issue with the ASD datasets. We pooled datasets with information only in the visible and datasets with information from 350 to 2500 nm. The jump comes from pooling these datasets. I had removed this plot for this reason.

**Comment by serbinsh** [comment]
Closing this issue
