### ISSUE TITLE
Add Whittaker plot to repo

### ISSUE THREAD

**Issue by serbinsh** [plantphys/gsti#77]
TODO: Add something similar to the plot in Serbin et al, 2019

![Study_Site_Map_and_Whittaker_Plot_main_text](https://github.com/user-attachments/assets/f58b156c-3f69-42b3-9cec-327b39d2b889)

**Comment by JulienLamour** [comment]
![Whittaker_plot](https://github.com/user-attachments/assets/731ed39b-8643-4055-b9a7-871f1c4ac191)

I was quicker than you ;)
