### ISSUE TITLE
Finding a way to flag the training and validation observations

### ISSUE THREAD

**Issue by JulienLamour** [plantphys/gsti#81]
It would be great to flag the observations in the database V1 so people can test and compare their models using always the same observations for training and validating them. This would allow different teams to compare their models rigrously.
We could use a 80% / 20% calibration / validation structure and flag the observations of the database by adding a column "training_validation". If you have other ideas, please let me know.

Cheers

Julien

**Comment by fupenghzau** [comment]
That seems to be a good idea. Others can also select their own ways to split the dataset. Any specific split would be appropriate?

**Comment by Daryl-YANG** [comment]
That sounds good! I am not 100% if others will use the the same training vs. validation when they use the data, but I think it is good for folks to know which is training and which is val in our model at least.

**Comment by JulienLamour** [comment]
Thanks! I now save the training and validation datasets so the results can be reproduced and compared
